//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author_Book
    {
        public int Author_AuthorId { get; set; }
        public int Book_AuthorId { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Author Author1 { get; set; }
    }
}
