//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WishList
    {
        public int WishListId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string BookName { get; set; }
        public string AuthorName { get; set; }
        public string Photo { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual User User { get; set; }
    }
}
